name: Run scraper script

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Run Script
      run: node scrapper.js
